# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0430\u043a\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('avg_price', models.DecimalField(decimal_places=15, help_text='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0446\u0435\u043d\u0430', max_digits=35, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f')),
                ('portfolie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='portfolio.Portfolio', verbose_name='\u041f\u043e\u0440\u0442\u0444\u0435\u043b\u044c')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Share', verbose_name='\u0410\u043a\u0446\u0438\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, '\u041f\u0440\u043e\u0434\u0430\u0436\u0430'), (1, '\u041f\u043e\u043a\u0443\u043f\u043a\u0430')], help_text='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043f\u043e \u043a\u0430\u0442\u0438\u0432\u0443: \u043f\u043e\u043a\u0443\u043f\u043a\u0430/\u043f\u0440\u043e\u0434\u0430\u0436\u0430', verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0430\u043a\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('price', models.DecimalField(decimal_places=15, help_text='\u0426\u0435\u043d\u0430 \u043e\u0434\u043d\u043e\u0439 \u0446\u0435\u043d\u043d\u043e\u0439 \u0434\u0443\u043c\u0430\u0433\u0438', max_digits=35, verbose_name='\u0426\u0435\u043d\u0430')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u0414\u0430\u0442\u0430 \u0441\u0434\u0435\u043b\u043a\u0438', verbose_name='\u0414\u0430\u0442\u0430')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('share_item', models.ForeignKey(help_text='\u0421\u0434\u0435\u043b\u043a\u0430 \u043f\u043e \u043a\u0430\u043a\u043e\u043c\u0443 \u0430\u043a\u0442\u0438\u0432\u0443', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shares.ShareItem', verbose_name='\u0410\u043a\u0442\u0438\u0432')),
            ],
        ),
    ]
