# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20170216_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0430\u043a\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('legal_close_price', models.DecimalField(decimal_places=15, help_text='\u0426\u0435\u043d\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f', max_digits=35, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442\u0438\u044f')),
                ('avg_price', models.DecimalField(decimal_places=15, help_text='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0446\u0435\u043d\u0430', max_digits=35, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0442\u043e\u0440\u0433\u043e\u0432')),
                ('share_item', models.ForeignKey(help_text='\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0430\u043a\u0442\u0438\u0432\u0430', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shares.ShareItem', verbose_name='\u0410\u043a\u0442\u0438\u0432')),
            ],
        ),
        migrations.AlterField(
            model_name='sharetransaction',
            name='price',
            field=models.DecimalField(decimal_places=15, help_text='\u0426\u0435\u043d\u0430 \u043e\u0434\u043d\u043e\u0439 \u0446\u0435\u043d\u043d\u043e\u0439 \u0431\u0443\u043c\u0430\u0433\u0438', max_digits=35, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
