# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_auto_20170216_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareitemhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sharetransaction',
            options={'ordering': ['-date']},
        ),
    ]
