# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_auto_20170216_2130'),
        ('portfolio', '0001_initial'),
        ('shares', '0004_auto_20170216_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shareitem',
            unique_together=set([('share', 'portfolio')]),
        ),
        migrations.AlterUniqueTogether(
            name='shareitemhistory',
            unique_together=set([('share_item', 'date')]),
        ),
    ]
