# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20170218_2053'),
        ('shares', '0006_auto_20170217_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareItemDividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=15, help_text='\u0421\u0443\u043c\u043c\u0430 \u0432\u044b\u043f\u043b\u0430\u0442 \u0431\u0435\u0437 \u043d\u0430\u043b\u043e\u0433\u0430', max_digits=35, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0432\u044b\u043f\u043b\u0430\u0442')),
                ('tax', models.DecimalField(decimal_places=15, default=Decimal('0.13'), help_text='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u043d\u0430\u043b\u043e\u0433\u0430', max_digits=35, verbose_name='\u041d\u0414\u0424\u041b, %')),
                ('checked', models.BooleanField(default=False, help_text='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043e\u0432 \u043d\u0430 \u0441\u0447\u0435\u0442', verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0430')),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.DividendHistory', verbose_name='\u0414\u0438\u0432\u0438\u0434\u0435\u043d\u0434')),
                ('share_item', models.ForeignKey(help_text='\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043e\u0432', on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='shares.ShareItem', verbose_name='\u0410\u043a\u0442\u0438\u0432')),
            ],
        ),
    ]
