# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20170218_2053'),
        ('shares', '0007_shareitemdividend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareitemdividend',
            options={'ordering': ['-dividend__date_registry_close'], 'verbose_name': '\u0412\u044b\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0439 \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434', 'verbose_name_plural': '\u0412\u044b\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0435 \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u044b'},
        ),
        migrations.RenameField(
            model_name='shareitemdividend',
            old_name='price',
            new_name='price_no_tax',
        ),
        migrations.AlterUniqueTogether(
            name='shareitemdividend',
            unique_together=set([('share_item', 'dividend')]),
        ),
    ]
