# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0009_shareitemdividend_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareitemdividend',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c \u043d\u0430 \u0434\u0430\u0442\u0443 \u0432\u044b\u043f\u043b\u0430\u0442\u044b \u0441 \u0443\u0447\u0435\u0442\u043e\u043c \u043d\u0430\u043b\u043e\u0433\u0430, %', max_digits=35, null=True, verbose_name='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c, %'),
        ),
        migrations.AlterField(
            model_name='shareitemdividend',
            name='tax',
            field=models.DecimalField(decimal_places=15, default=Decimal('13'), help_text='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u043d\u0430\u043b\u043e\u0433\u0430', max_digits=35, verbose_name='\u041d\u0414\u0424\u041b, %'),
        ),
    ]
