# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0012_auto_20170306_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='volume',
            field=models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0431\u0443\u043c\u0430\u0433', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
