# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0015_auto_20170306_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareitemhistory',
            options={'ordering': ['-date'], 'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043f\u0430\u043a\u0435\u0442\u0430 \u0431\u0443\u043c\u0430\u0433', 'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u043f\u0430\u043a\u0435\u0442\u043e\u0432 \u0431\u0443\u043c\u0430\u0433'},
        ),
    ]
