# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0016_auto_20170306_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareitemhistory',
            options={'ordering': ['-date'], 'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043f\u0430\u043a\u0435\u0442\u0430 \u0430\u043a\u0446\u0438\u0439', 'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u043f\u0430\u043a\u0435\u0442\u043e\u0432 \u0430\u043a\u0446\u0438\u0439'},
        ),
        migrations.AlterField(
            model_name='shareitemdividend',
            name='checked',
            field=models.BooleanField(default=False, help_text='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043d\u0430 \u0441\u0447\u0435\u0442', verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0430'),
        ),
    ]
