# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='\u041a\u043e\u0434 \u0432\u0430\u043b\u044e\u0442\u044b, \u043d\u0435 \u0431\u043e\u043b\u0435\u0435 1024-\u0445 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432', max_length=1024, verbose_name='\u041a\u043e\u0434')),
                ('short_name', models.CharField(help_text='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435, \u043d\u0435 \u0431\u043e\u043b\u0435\u0435 1024-\u0445 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432', max_length=1024, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435, \u043d\u0435 \u0431\u043e\u043b\u0435\u0435 1024-\u0445 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432', max_length=1024, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0412\u0430\u043b\u044e\u0442\u0430',
                'verbose_name_plural': '\u0412\u0430\u043b\u044e\u0442\u044b',
            },
        ),
    ]
