# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=15, help_text='\u041a\u0443\u0440\u0441 \u0432\u0430\u043b\u044e\u0442\u044b 1 \u0432 \u0446\u0435\u043d\u0435 2 (\u0437\u0430 \u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0432\u0430\u043b\u044e\u0442\u044b 2 \u043c\u043e\u0436\u043d\u043e \u043a\u0443\u043f\u0438\u0442\u044c \u043e\u0434\u043d\u0443 \u0432\u0430\u043b\u044e\u0442\u0443 1)', max_digits=35, verbose_name='\u041a\u0443\u0440\u0441')),
                ('date', models.DateField(help_text='\u041d\u0430 \u043a\u0430\u043a\u0443\u044e \u0434\u0430\u0442\u0443 \u043a\u0443\u0440\u0441', verbose_name='\u0414\u0430\u0442\u0430')),
                ('currency1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates1', to='currency.Currency', verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 1')),
                ('currency2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates2', to='currency.Currency', verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430 2')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u041a\u0443\u0440\u0441 \u0432\u0430\u043b\u044e\u0442\u044b',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b \u0432\u0430\u043b\u044e\u0442',
            },
        ),
    ]
