# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharehistory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sharehistory',
            unique_together=set([('trade_date', 'share')]),
        ),
    ]
