# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_auto_20170217_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_flag', models.BooleanField(help_text='\u041f\u0440\u043e\u0433\u043d\u043e\u0437 \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043d\u043e\u0439 \u0432\u044b\u043f\u043b\u0430\u0442\u044b', verbose_name='\u041f\u0440\u043e\u0433\u043d\u043e\u0437')),
                ('date_registry_close', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f \u0440\u0435\u0435\u0441\u0442\u0440\u0430')),
                ('date_payment', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u043f\u043b\u0430\u0442\u044b')),
                ('dividend', models.DecimalField(blank=True, decimal_places=15, help_text='\u0420\u0430\u0437\u043c\u0435\u0440 \u0432\u044b\u043f\u043b\u0430\u0442\u044b \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u0430 \u043d\u0430 \u043e\u0434\u043d\u0443 \u0430\u043a\u0446\u0438\u044e', max_digits=35, null=True, verbose_name='\u0414\u0438\u0432\u0438\u0434\u0435\u043d\u0434')),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=3, help_text='\u041a\u0430\u043a\u043e\u0439 \u043f\u0440\u043e\u0446\u0435\u043d\u0442 \u043e\u0442 \u043f\u0440\u0438\u0431\u044b\u043b\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438 \u0431\u044b\u043b \u0432\u044b\u043f\u043b\u0430\u0447\u0435\u043d \u0432 \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0435 \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043e\u0432', max_digits=6, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043e\u0442 \u043f\u0440\u0438\u0431\u044b\u043b\u0438')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='securities.Share', verbose_name='\u0410\u043a\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0414\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043d\u0430\u044f \u0432\u044b\u043f\u043b\u0430\u0442\u0430',
                'verbose_name_plural': '\u0414\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043d\u044b\u0435 \u0432\u044b\u043f\u043b\u0430\u0442\u044b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dividendhistory',
            unique_together=set([('share', 'date_registry_close')]),
        ),
    ]
