# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20170218_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendhistory',
            name='profit_percent',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='\u041a\u0430\u043a\u043e\u0439 \u043f\u0440\u043e\u0446\u0435\u043d\u0442 \u043e\u0442 \u043f\u0440\u0438\u0431\u044b\u043b\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438 \u0431\u044b\u043b \u0432\u044b\u043f\u043b\u0430\u0447\u0435\u043d \u0432 \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0435 \u0434\u0438\u0432\u0438\u0434\u0435\u043d\u0434\u043e\u0432', max_digits=10, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043e\u0442 \u043f\u0440\u0438\u0431\u044b\u043b\u0438'),
        ),
    ]
