# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0009_bondhistory_yield_close'),
        ('portfolio', '0002_auto_20170217_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0430\u043a\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('avg_price', models.DecimalField(decimal_places=15, help_text='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0446\u0435\u043d\u0430, %', max_digits=35, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f, %')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Bond', verbose_name='\u041e\u0431\u043b\u0438\u0448\u0430\u0446\u0438\u044f')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='portfolio.Portfolio', verbose_name='\u041f\u043e\u0440\u0442\u0444\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u043e\u0431\u043b\u0438\u0448\u0430\u0446\u0438\u0439',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442\u044b \u043e\u0431\u043b\u0438\u0448\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='BondTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, '\u041f\u0440\u043e\u0434\u0430\u0436\u0430'), (1, '\u041f\u043e\u043a\u0443\u043f\u043a\u0430')], help_text='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043f\u043e \u043a\u0430\u0442\u0438\u0432\u0443: \u043f\u043e\u043a\u0443\u043f\u043a\u0430/\u043f\u0440\u043e\u0434\u0430\u0436\u0430', verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('price', models.DecimalField(decimal_places=15, help_text='\u0426\u0435\u043d\u0430 \u043e\u0434\u043d\u043e\u0439 \u0446\u0435\u043d\u043d\u043e\u0439 \u0431\u0443\u043c\u0430\u0433\u0438', max_digits=35, verbose_name='\u0426\u0435\u043d\u0430')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='\u0414\u0430\u0442\u0430 \u0441\u0434\u0435\u043b\u043a\u0438', verbose_name='\u0414\u0430\u0442\u0430')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('key', models.CharField(blank=True, help_text='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0441\u0434\u0435\u043b\u043a\u0438 \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u043f\u0430\u0440\u0441\u0438\u043d\u0433\u0430', max_length=1024, null=True, verbose_name='\u041a\u043b\u044e\u0447 \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('bond_item', models.ForeignKey(help_text='\u0421\u0434\u0435\u043b\u043a\u0430 \u043f\u043e \u043a\u0430\u043a\u043e\u043c\u0443 \u0430\u043a\u0442\u0438\u0432\u0443', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bonds.BondItem', verbose_name='\u0410\u043a\u0442\u0438\u0432')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0421\u0434\u0435\u043b\u043a\u0430',
                'verbose_name_plural': '\u0421\u0434\u0435\u043b\u043a\u0438',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bonditem',
            unique_together=set([('bond', 'portfolio')]),
        ),
    ]
