# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('legal_close_price', models.DecimalField(decimal_places=15, help_text='\u0426\u0435\u043d\u0430 \u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f', max_digits=35, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442\u0438\u044f')),
                ('avg_price', models.DecimalField(decimal_places=15, help_text='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0446\u0435\u043d\u0430', max_digits=35, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f')),
                ('accint', models.DecimalField(blank=True, decimal_places=15, help_text='\u041d\u0430\u043a\u043e\u043f\u043b\u0435\u043d\u043d\u044b\u0439 \u043a\u0443\u043f\u043e\u043d\u043d\u044b\u0439 \u0434\u043e\u0445\u043e\u0434 (\u041d\u041a\u0414), \u043f\u043e \u043e\u0434\u043d\u043e\u0439 \u0446\u0435\u043d\u043d\u043e\u0439 \u0431\u0443\u043c\u0430\u0433\u0435', max_digits=35, null=True, verbose_name='\u041d\u041a\u0414')),
                ('yield_close', models.DecimalField(blank=True, decimal_places=15, help_text='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c \u043f\u043e \u0446\u0435\u043d\u0435 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u0441\u0434\u0435\u043b\u043a\u0438, % \u0433\u043e\u0434\u043e\u0432\u044b\u0445', max_digits=35, null=True, verbose_name='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c, % \u0433\u043e\u0434\u043e\u0432\u044b\u0445 - \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u0441\u0434\u0435\u043b\u043a\u0438')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0442\u043e\u0440\u0433\u043e\u0432')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u043f\u0430\u043a\u0435\u0442\u0430 \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u043f\u0430\u043a\u0435\u0442\u043e\u0432 \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.AlterModelOptions(
            name='bonditem',
            options={'verbose_name': '\u041f\u0430\u043a\u0435\u0442 \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439', 'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442\u044b \u043e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u0439'},
        ),
        migrations.AlterField(
            model_name='bonditem',
            name='bond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Bond', verbose_name='\u041e\u0431\u043b\u0438\u0433\u0430\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='bonditemhistory',
            name='bond_item',
            field=models.ForeignKey(help_text='\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0430\u043a\u0442\u0438\u0432\u0430', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bonds.BondItem', verbose_name='\u0410\u043a\u0442\u0438\u0432'),
        ),
        migrations.AlterUniqueTogether(
            name='bonditemhistory',
            unique_together=set([('bond_item', 'date')]),
        ),
    ]
