# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_auto_20170304_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonditem',
            name='avg_price',
            field=models.DecimalField(decimal_places=15, help_text='\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0446\u0435\u043d\u0430', max_digits=35, verbose_name='\u0421\u0440\u0435\u0434\u043d\u044f\u044f'),
        ),
        migrations.AlterField(
            model_name='bonditem',
            name='volume',
            field=models.IntegerField(help_text='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0431\u0443\u043c\u0430\u0433', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
