# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0006_bondtransaction_accint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondItemCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_no_tax', models.DecimalField(decimal_places=15, help_text='\u0421\u0443\u043c\u043c\u0430 \u0432\u044b\u043f\u043b\u0430\u0442 \u0431\u0435\u0437 \u043d\u0430\u043b\u043e\u0433\u0430', max_digits=35, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0432\u044b\u043f\u043b\u0430\u0442')),
                ('tax', models.DecimalField(decimal_places=15, default=Decimal('13'), help_text='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u043d\u0430\u043b\u043e\u0433\u0430', max_digits=35, verbose_name='\u041d\u0414\u0424\u041b, %')),
                ('checked', models.BooleanField(default=False, help_text='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043d\u0430 \u0441\u0447\u0435\u0442', verbose_name='\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0430')),
                ('percent', models.DecimalField(blank=True, decimal_places=15, help_text='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c \u043d\u0430 \u0434\u0430\u0442\u0443 \u0432\u044b\u043f\u043b\u0430\u0442\u044b \u0441 \u0443\u0447\u0435\u0442\u043e\u043c \u043d\u0430\u043b\u043e\u0433\u0430, %', max_digits=35, null=True, verbose_name='\u0414\u043e\u0445\u043e\u0434\u043d\u043e\u0441\u0442\u044c, %')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u043f\u043b\u0430\u0442\u044b')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('bond_item', models.ForeignKey(help_text='\u0410\u043a\u0442\u0438\u0432', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='bonds.BondItem', verbose_name='\u0410\u043a\u0442\u0438\u0432')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0412\u044b\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0439 \u043a\u0443\u043f\u043e\u043d',
                'verbose_name_plural': '\u0412\u044b\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0435 \u043a\u0443\u043f\u043e\u043d\u044b',
            },
        ),
    ]
