# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0440\u0442\u0444\u0435\u043b\u044f, \u043d\u0435 \u0431\u043e\u043b\u0435\u0435 1024 \u0441\u0438\u043c\u0432\u043e\u043b\u0430', max_length=1024, verbose_name='\u041f\u043e\u0440\u0442\u0444\u0435\u043b\u044c')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
